package com.example.myapplication.Model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.databinding.Bindable;

/**
 * Entity mapped to table STUDENT.
 */
public class Student{

    @Bindable
    public String name;
    public String age;

    public Student() {
    }

    public Student(String name, String age) {
        this.name = name;
        this.age = age;
    }
}
